[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trufnetwork-adapters"
version = "0.1.0"
description = "A collection of prefect tasks and examples ingesting data into TSN"
readme = "README.md"
dependencies = [
    "prefect-client",
    "truflation-data@git+https://github.com/truflation/truflation.git@deploy-production-20241008",
    "trufnetwork-sdk-py@git+https://github.com/trufnetwork/sdk-py.git@3787c754326c63e5644a1fa9ab8c8201fa14b95a",
    "PyGithub",
    "pandera",
    "pandas",
]

[project.optional-dependencies]
argentina = [
    "beautifulsoup4",
    "dateparser"
]

[tool.setuptools]
packages = {find = {where = ["."]}}
package-dir = {"" = "."}

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')"
]
pythonpath = ["src"]
addopts = "--import-mode=importlib"
testpaths = ["tests"]
